services:
  prediction-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: prediction-engine:1.0
    container_name: prediction-engine
    restart: unless-stopped
    network_mode: host
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SPRING_PROFILES_ACTIVE=prod
      - CONSUMABLE_FOLDER_PATH=/app/consumable
    volumes:
      - ./consumable:/app/consumable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/" ]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

